// AUTOGENERATED Components module
#[allow(dead_code)]
pub mod badge;
#[allow(dead_code)]
pub mod button;
#[allow(dead_code)]
pub mod card;
#[allow(dead_code)]
pub mod checkbox;
pub mod dialog;
#[allow(dead_code)]
pub mod input;
#[allow(dead_code)]
pub mod label;
